service: myService

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-1

functions:
  dispatch:
    handler: handler.dispatch
    events:
      - http: ANY {proxy+}
      - http: ANY dispatch
